version: '2'

services:
  percona-odk:
    image: percona:5.5.43
    ports:
     - "3306:3306"
    volumes:
     - mysqldata:/var/lib/mysql
    container_name: percona-odk
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: odenktools
      MYSQL_USER: odenktools
      MYSQL_DATABASE: location_service
      MYSQL_PASSWORD: odenktools
  spring-query-service:
    image: odenktools/spring-location-service:v1
    container_name: spring-location-service
    depends_on:
     - percona-odk
    ports:
     - "8080:9001"
volumes:
  mysqldata: