version: '2'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    container_name: odk-rabbitmq
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  percona-location-service:
    image: percona:5.5.43
    ports:
     - "33060:3306"
    container_name: percona-location-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: odenktools
      MYSQL_USER: odenktools
      MYSQL_DATABASE: location_service
      MYSQL_PASSWORD: odenktools

  percona-account-service:
    image: percona:5.5.43
    ports:
     - "33061:3306"
    container_name: percona-account-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: odenktools
      MYSQL_USER: odenktools
      MYSQL_DATABASE: account_service
      MYSQL_PASSWORD: odenktools

  config-service:
    image: odenktools/spring-config-service:v1
    restart: always
    ports:
     - "8888:8888"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry-service:
    image: odenktools/spring-registry-service:v1
    ports:
     - "8761:8761"
    restart: always
    depends_on:
      - config-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-service:
    image: odenktools/spring-gateway-service:v1
    ports:
     - "4000:4000"
    restart: always
    depends_on:
      - config-service

  location-service:
    image: odenktools/spring-location-service:v1
    ports:
     - "9001:9001"
    restart: always
    depends_on:
      - config-service
      - percona-location-service

  account-service:
    image: odenktools/spring-account-service:v1
    ports:
     - "9002:9002"
    restart: always
    depends_on:
      - config-service
      - percona-account-service