info:
  component: Config Server
spring:
  application:
    name: config-service
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/odenktools/spring-cloud-config
server:
  port: 8888
  address: localhost
management:
  context_path: /admin
security:
  user:
   name: root
   password: s3cr3t