spring:
  application:
    name: config
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: dev,native
server:
  port: 8888
security:
  user:
    name: root
    password: secret